// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlew0x276Vz-0MtoioDUnE5et7zQaTh0Q',
    appId: '1:617404280916:web:de9364abc0d5cd513fbdc1',
    messagingSenderId: '617404280916',
    projectId: 'campusconnect-25317',
    authDomain: 'campusconnect-25317.firebaseapp.com',
    storageBucket: 'campusconnect-25317.firebasestorage.app',
    measurementId: 'G-80986FN9E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr3gQ75OLp4a4aVpEvY82Q4AKS52gBNOs',
    appId: '1:617404280916:android:8188345e96d62ab83fbdc1',
    messagingSenderId: '617404280916',
    projectId: 'campusconnect-25317',
    storageBucket: 'campusconnect-25317.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLw1yB9986jzKwptG3Caapgx0BsG2FxxY',
    appId: '1:617404280916:ios:7049a8f69ade617d3fbdc1',
    messagingSenderId: '617404280916',
    projectId: 'campusconnect-25317',
    storageBucket: 'campusconnect-25317.firebasestorage.app',
    iosBundleId: 'com.example.campusConnectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLw1yB9986jzKwptG3Caapgx0BsG2FxxY',
    appId: '1:617404280916:ios:7049a8f69ade617d3fbdc1',
    messagingSenderId: '617404280916',
    projectId: 'campusconnect-25317',
    storageBucket: 'campusconnect-25317.firebasestorage.app',
    iosBundleId: 'com.example.campusConnectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlew0x276Vz-0MtoioDUnE5et7zQaTh0Q',
    appId: '1:617404280916:web:de87745d6cff73b53fbdc1',
    messagingSenderId: '617404280916',
    projectId: 'campusconnect-25317',
    authDomain: 'campusconnect-25317.firebaseapp.com',
    storageBucket: 'campusconnect-25317.firebasestorage.app',
    measurementId: 'G-950Y9EB5M8',
  );
}
